source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'
inhibit_all_warnings!

xcodeproj 'LGViewsDemo'

target 'LGViewsDemo' do
    pod 'LGViews', :path => '../'
    pod 'LGHelper', '~> 1.0.0'
end
